"""M15: reply detection. Done when: 100% correct on the bounce / OOO / reply fixtures.

Each fixture in tests/fixtures is a realistic message (Gmail, Exchange, Outlook, German OOO, ...)
delivered into the fake Gmail and taken through the real inbox sync, which labels it.
"""
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app import inbox_sync
from app.main import app
from fakes import db

FIXTURES = Path(__file__).parent / "fixtures"

EXPECTED = {  # fixture -> (label, bounce_type, links to the Acme email?)
    "gmail_hard_bounce.eml": ("bounce", "hard", True),
    "gmail_delayed.eml": ("bounce", "soft", True),
    "exchange_ndr.eml": ("bounce", "hard", True),
    "plain_text_bounce.eml": ("bounce", "hard", True),
    "outlook_ooo.eml": ("auto_reply", None, True),
    "german_ooo.eml": ("auto_reply", None, True),
    "header_only_autoreply.eml": ("auto_reply", None, True),
    "thread_reply.eml": ("reply", None, True),
    "gmail_thread_reply_no_headers.eml": ("reply", None, True),
    "colleague_reply.eml": ("reply", None, True),
    "company_newsletter.eml": ("unrelated", None, False),
    "company_notification_autogenerated.eml": ("unrelated", None, False),  # Auto-Submitted header only
    "company_noreply.eml": ("unrelated", None, False),                     # no-reply sender only
    "not_emailed_company.eml": ("unrelated", None, False),
}
IN_OUR_THREAD = {"gmail_thread_reply_no_headers.eml"}  # no reply headers; only Gmail's thread links it


@pytest.fixture
def gamma(client):
    """A company with a contact that was never emailed."""
    cid = client.post("/companies", json={"name": "Gamma", "domain": "gamma.fr"}).json()["id"]
    client.post(f"/companies/{cid}/contacts", json={"email": "jobs@gamma.fr"})
    return cid


def deliver(gmail, sent, name):
    acme_id, acme_mid, acme_thread, _ = sent["acme"]
    raw = (FIXTURES / name).read_text(encoding="utf-8")
    raw = raw.replace("{{OUR_MSGID}}", acme_mid).replace("{{RCPT}}", "jobs@acme.de")
    return gmail.inbound_raw(raw.encode(), thrid=acme_thread if name in IN_OUR_THREAD else None)


def row(test_url, gm):
    r = db(test_url, "SELECT label, bounce_type, outbound_email_id, label_rule FROM inbound_messages "
                     "WHERE gmail_msgid = %s", (gm,))
    return r[0] if r else None


def test_every_fixture_is_covered():
    assert {p.name for p in FIXTURES.glob("*.eml")} == set(EXPECTED)


@pytest.mark.parametrize("name", sorted(EXPECTED))
def test_fixture_is_labelled_correctly(name, sent, gamma, gmail, test_url):
    gm = deliver(gmail, sent, name)
    assert inbox_sync.sync_once()["action"] == "synced"
    got = row(test_url, gm)
    assert got is not None, f"{name} was not stored"
    label, bounce_type, linked = EXPECTED[name]
    assert (got[0], got[1]) == (label, bounce_type), f"{name}: {got[3]}"
    assert (got[2] == sent["acme"][0]) is linked
    assert got[3]  # every label says which rule matched


def test_fixture_score_is_100_percent(sent, gamma, gmail, test_url):
    """All fixtures in one mailbox, one sync: the done-criterion as a single number."""
    ids = {name: deliver(gmail, sent, name) for name in sorted(EXPECTED)}
    inbox_sync.sync_once()
    correct = sum(1 for name, gm in ids.items()
                  if (row(test_url, gm) or (None, None))[:2] == EXPECTED[name][:2])
    assert correct == len(EXPECTED), f"{correct}/{len(EXPECTED)}"


# ---------- effects: record and protect, never send ----------

def queue_extra_acme_email(test_url, company_id):
    """A second approved+queued email to Acme (inserted directly: the cooldown check would refuse it)."""
    db(test_url, "INSERT INTO outbound_emails (to_email, subject, body, company_id, status, approved_at, "
                 "approved_content_hash) VALUES ('hr@acme.de', 'Follow', 'b', %s, 'queued', now(), "
                 "email_content_hash('hr@acme.de', 'Follow', 'b'))", (company_id,))


def test_reply_sets_stage_and_cancels_pending_emails(sent, gmail, test_url):
    acme_company = sent["acme"][3]
    queue_extra_acme_email(test_url, acme_company)
    before = len(gmail.delivered)
    deliver(gmail, sent, "thread_reply.eml")
    inbox_sync.sync_once()
    assert db(test_url, "SELECT stage FROM companies WHERE id = %s", (acme_company,))[0][0] == "replied"
    pending = db(test_url, "SELECT status, cancel_reason FROM outbound_emails WHERE to_email = 'hr@acme.de'")[0]
    assert pending == ("cancelled", "company replied; review first")
    assert len(gmail.delivered) == before  # nothing was sent in response


def test_auto_reply_changes_nothing(sent, gmail, test_url):
    deliver(gmail, sent, "outlook_ooo.eml")
    inbox_sync.sync_once()
    assert db(test_url, "SELECT stage FROM companies WHERE id = %s", (sent["acme"][3],))[0][0] == "contacted"


def test_reply_does_not_reopen_a_closed_lead(sent, client, gmail, test_url):
    client.post("/leads/stage", json={"company_ids": [sent["acme"][3]], "stage": "closed", "close_reason": "no fit"})
    deliver(gmail, sent, "thread_reply.eml")
    inbox_sync.sync_once()
    assert db(test_url, "SELECT stage FROM companies WHERE id = %s", (sent["acme"][3],))[0][0] == "closed"


def test_hard_bounce_marks_email_and_blocks_the_address(sent, client, gmail, test_url):
    deliver(gmail, sent, "gmail_hard_bounce.eml")
    inbox_sync.sync_once()
    e = db(test_url, "SELECT bounce_type, bounced_at IS NOT NULL, bounce_detail FROM outbound_emails WHERE id = %s",
           (sent["acme"][0],))[0]
    assert e[0] == "hard" and e[1] and e[2].startswith("5.1.1")
    blocks = db(test_url, "SELECT email, reason FROM suppressions WHERE lifted_at IS NULL")
    assert blocks == [("jobs@acme.de", "hard bounce (5.1.1)")]
    assert client.get("/suppressions/check", params={"email": "jobs@acme.de"}).json()["suppressed"] is True
    actions = [a for (a,) in db(test_url, "SELECT action FROM audit_log WHERE entity_type = 'outbound_email' "
                                          "AND entity_id = %s", (sent["acme"][0],))]
    assert "outbound_email.bounced" in actions


def test_soft_bounce_does_not_block(sent, gmail, test_url):
    deliver(gmail, sent, "gmail_delayed.eml")
    inbox_sync.sync_once()
    assert db(test_url, "SELECT bounce_type FROM outbound_emails WHERE id = %s", (sent["acme"][0],))[0][0] == "soft"
    assert db(test_url, "SELECT count(*) FROM suppressions")[0][0] == 0


def test_relabel_is_idempotent(sent, client, gmail, test_url):
    for name in ("gmail_hard_bounce.eml", "thread_reply.eml", "company_newsletter.eml"):
        deliver(gmail, sent, name)
    inbox_sync.sync_once()
    assert client.post("/inbox/relabel").json() == {"relabeled": 0}
    assert db(test_url, "SELECT count(*) FROM suppressions")[0][0] == 1
    assert db(test_url, "SELECT count(*) FROM audit_log WHERE action = 'outbound_email.bounced' AND entity_id = %s",
              (sent["acme"][0],))[0][0] == 1  # the audit log is append-only across tests: scope to this email


def test_labels_in_inbox_api(sent, client, gmail, test_url):
    for name in ("thread_reply.eml", "outlook_ooo.eml", "company_newsletter.eml"):
        deliver(gmail, sent, name)
    inbox_sync.sync_once()
    assert TestClient(app).post("/inbox/relabel").status_code == 401
    assert {m["label"] for m in client.get("/inbox").json()} == {"reply", "auto_reply", "unrelated"}
    replies = client.get("/inbox", params={"label": "reply"}).json()
    assert [m["subject"] for m in replies] == ["Re: Hello Acme"] and replies[0]["label_rule"]
    assert client.get("/inbox", params={"label": "spam"}).status_code == 422
    events = [e["action"] for e in client.get(f"/companies/{sent['acme'][3]}/activity").json()]
    assert "inbound.labeled" in events
